import streamlit as st
import datetime
import requests
import sys

BASE_URL = "https://localhost:8000"  #Backend endpoint

st.set_page_config(
    page_title= " Travle Planner Agentic Application",
    page_icon= "",
    layout= "centered",
    initial_sidebar_state="expanded"
)

st.title(" Travle Planner Agentic Application")

#initialize chat history

if "messages" not in st.session_state:
    st.session_state.messages = []


st.header(" How can i help you in planning a trip? Let me know where do you want to visit.")

with st.form(key= "query_form",clear_on_submit=True):
    user_input = st.text_input("User_input", placeholder= "e.g. plan a trip to goa for 5 days")
    submit_button = st.form_submit_button("send")

if submit_button and user_input.strip():
    try:
        # show user message
        #show thinking spinner while backend processes

        with st.spinner("Bot is thinking...."):
            payload = {"question": user_input}
            response = requests.post(f"{BASE_URL}/query", json=payload)


        if response.status_code ==200:
            answer = response.json().get("answer","No answer returned.")
            markdown_content = f"""# AI Travel plan

            # **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}
            # **Created by:** Atriyo's Travel Agent


            ---

            {answer}

            ---

            * This travel was generated by AI. Please verify all the information, especially prices, operations """
            st.markdown(markdown_content)
        else:
            st.error("Bot failed to respond: " + response.text)

    except Exception as e:
        raise f"The response failed due to {e}"